// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://wlqsfutahioyciqkwast.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6IndscXNmdXRhaGlveWNpcWt3YXN0Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTg2MDMxMjgsImV4cCI6MjA3NDE3OTEyOH0.IdHnZ_zP8jQkJrKYi5bCYvQBYwqbgZgabosyqHGuB0k";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});